#!/usr/bin/env python3
"""The three shots of the Xeet teaser, generated by MiniMax Hailuo.

    python3 promo/gen.py            # skips any clip already on disk

Shot 1 is made from nothing; shots 2 and 3 start from promo/first-frame-wide.png
so the mark in them is OUR mark and not a model's idea of one. Clips come back
longer than they are used — the cut is made later, in the edit.

curl rather than urllib: this machine has no CA bundle Python will accept.
"""
import base64, json, os, subprocess, sys, time

KEY = dict(l.strip().split("=", 1) for l in open(os.path.expanduser("~/.config/minimax.env")) if "=" in l)["MINIMAX_API_KEY"]
API = "https://api.minimax.io/v1"
HERE = os.path.dirname(os.path.abspath(__file__))
FRAME = os.path.join(HERE, "first-frame-wide.png")

NEG = ("No text, no letters, no words, no logos other than the object itself, no numbers, "
       "no user interface, no people, no hands, no color — black and cold white only.")

ONE = {"first": FRAME, "duration": 10, "prompt": (
    "A single continuous shot. Total darkness, then a glossy white object with soft bevels is revealed in "
    "the center of the frame as the camera slowly pulls back from an extreme close-up of its edge. A single "
    "cold light sweeps slowly along the bevel from left to right and lingers for a moment on the tip of the "
    "arrow. The camera drifts a few degrees around the object — parallax only. Then the light decays, the "
    "volumetric haze disperses and the frame settles into pure deep black. The object never deforms, never "
    "melts, never crumples, never rotates on itself and never changes shape — only the light and the camera "
    "move. Slow, controlled, cinematic product-commercial lighting, deep blacks, shallow depth of field. "
    "Monochrome: black and cold white only. " + NEG)}

MELT = {"first": FRAME, "duration": 6, "prompt": (
    "The glossy white mark in the center of pure blackness begins to lose its edges: the material boils and "
    "breaks away into hundreds of small glossy white droplets shaped like teardrops with trailing tails, like "
    "liquid mercury under a single cold light. The droplets spiral outward counter-clockwise into a slow "
    "swirling vortex ring around the center of the frame, tails curving along their path, merging and "
    "separating with surface tension. Then the vortex contracts and the droplets flow back toward the middle, "
    "gathering into one calm horizontal band of liquid metal that settles and goes still. Static camera, no "
    "zoom, no shake. Monochrome: black and cold white only, deep blacks, glossy specular highlights, soft "
    "volumetric glow. " + NEG)}

SHOTS = {
    "s1": dict(first=None, prompt=(
        "Pitch-black void. A thick liquid white material, like molten porcelain lit from within, "
        "slowly rises and coils in the center of the frame under a single cold key light. It has no "
        "recognisable shape yet, it is still gathering. Soft volumetric haze, deep blacks, glossy "
        "reflections, very shallow depth of field. Slow steady camera push-in. Cinematic product-commercial "
        "lighting, patient and expensive. " + NEG)),

    "s2": dict(first=FRAME, prompt=(
        "The glossy white mark holds steady in the center of the darkness. A single cold light sweeps "
        "slowly across its surface from left to right, revealing the soft bevels and the thickness of the "
        "material, and lingers for a moment on the tip of the arrow. The camera orbits a few degrees around "
        "it — parallax only. The shape never deforms, never melts, never changes. A faint volumetric glow "
        "breathes around it. Keep the object exactly as it is: do not redraw it. " + NEG)),

    "s3": dict(first=FRAME, prompt=(
        "The white mark pulses once. A bright ring of cold light expands outward from the tip of the arrow "
        "and dissolves into the haze, and the object recedes into the darkness as the light decays, leaving "
        "pure deep black. No shake, no debris, no sparks, no camera roll. " + NEG)),
}


def curl(args, data=None):
    cmd = ["curl", "-s", "-m", "120", "-H", f"Authorization: Bearer {KEY}"] + args
    if data is not None:
        cmd += ["-H", "Content-Type: application/json", "--data-binary", "@-"]
    out = subprocess.run(cmd, input=(json.dumps(data).encode() if data is not None else None),
                         capture_output=True).stdout
    try:
        return json.loads(out or b"{}")
    except json.JSONDecodeError:
        return {"raw": out[:300].decode(errors="replace")}


def submit(shot):
    body = {"model": "MiniMax-Hailuo-2.3", "prompt": shot["prompt"],
            "duration": shot.get("duration", 6), "resolution": "1080P", "prompt_optimizer": False}
    if shot["first"]:
        body["first_frame_image"] = "data:image/png;base64," + base64.b64encode(open(shot["first"], "rb").read()).decode()
    j = curl([f"{API}/video_generation"], body)
    if not j.get("task_id") and "1080" in str(j):      # plan may cap the size
        body["resolution"] = "768P"
        j = curl([f"{API}/video_generation"], body)
    return j


tasks = {}
import sys as _sys

# One shot at a time, picked on the command line: a generation costs quota, and
# a flag is cheaper than remembering to comment the others out.
if "--one" in _sys.argv:
    SHOTS = {"one": ONE}
elif "--melt" in _sys.argv:
    SHOTS = {"melt": MELT}

for name, shot in SHOTS.items():
    dst = os.path.join(HERE, f"{name}.mp4")
    if os.path.exists(dst):
        print(name, "already on disk, skipping", flush=True)
        continue
    j = submit(shot)
    err = (j.get("error") or {}).get("message") or (j.get("base_resp") or {}).get("status_msg", "")
    if not j.get("task_id"):
        print(name, "REJECTED:", err[:200] or j, flush=True)
        if "usage limit" in err or "insufficient" in err.lower():
            sys.exit("quota is out — nothing further will go through")
        continue
    tasks[name] = (j["task_id"], dst)
    print(name, "submitted", j["task_id"], flush=True)

t0 = time.time()
while tasks and time.time() - t0 < 2400:
    time.sleep(20)
    for name, (tid, dst) in list(tasks.items()):
        j = curl([f"{API}/query/video_generation?task_id={tid}"])
        st = j.get("status")
        if st == "Success":
            f = curl([f"{API}/files/retrieve?file_id={j['file_id']}"])
            subprocess.run(["curl", "-s", "-m", "300", "-o", dst, f["file"]["download_url"]], check=True)
            print(name, "DONE", os.path.getsize(dst), "bytes", f"{int(time.time() - t0)}s", flush=True)
            del tasks[name]
        elif st == "Fail":
            print(name, "FAILED", j.get("base_resp"), flush=True)
            del tasks[name]
        else:
            print(name, st, f"{int(time.time() - t0)}s", flush=True)
print("still running:", list(tasks))
